apiVersion: v1
kind: Pod
metadata:
  name: my-webapp
  labels:
    app: my-webapp
spec:
  containers:
    - name: my-webapp
      image: anaghavashista/myapp:v1
      ports:
        - containerPort: 8080
  restartPolicy: Always
